# Generated by Django 4.2.11 on 2024-04-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediwhistle', '0002_form'),
        ('mediwhistle', '0008_userprofile'),
    ]

    operations = [
    ]
