# Generated by Django 5.0.2 on 2024-04-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediwhistle', '0009_merge_0002_form_0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='practice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
