# Generated by Django 5.0.2 on 2024-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediwhistle', '0011_form_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(upload_to='form_files/'),
        ),
    ]
