# Generated by Django 5.0.2 on 2024-04-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediwhistle', '0013_form_status_form_title_form_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='document',
        ),
        migrations.AddField(
            model_name='comment',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mediwhistle.form'),
            preserve_default=False,
        ),
    ]
