# Generated by Django 5.0.2 on 2024-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediwhistle', '0014_remove_comment_document_comment_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='title',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='form_files/'),
        ),
    ]
